namespace EEGApplication.enums
{
    public enum eNSK_ALGO_F2_PROGRESS_LEVEL
    {
        NSK_ALGO_F2_PROGRESS_LEVEL_VERY_POOR = 1,
        NSK_ALGO_F2_PROGRESS_LEVEL_POOR,
        NSK_ALGO_F2_PROGRESS_LEVEL_FLAT,
        NSK_ALGO_F2_PROGRESS_LEVEL_GOOD,
        NSK_ALGO_F2_PROGRESS_LEVEL_GREAT
    }
}
